# basic configuration
markdown: kramdown
permalink: /:categories/:title/

# Change this tracking code with your own tracking code
ga_tracking_code: G-K08E4LNBWZ

# Some files we need to exclude, so Github can build the site
exclude: [Gemfile, Gemfile.lock, README.md]

defaults:
  -
    scope:
      path: "modules" # an empty string here means all files in the project
    values:
      layout: "course_page"

prose:
  media: img
  ignore:
    - /_includes
    - /_layouts
    - /_sass
    - /fonts
    - /js
    - /css

# Set some personal styles and logo for your course
# this is a hex value http://www.w3schools.com/tags/ref_colorpicker.asp
jumbotron_color: "#58D7CB"
# jumbotron_image: "img/rrf-site.png"
# jumbotron_mask: "img/jumbotron-mask.svg"
# jumbotron_icon: ""
